[package]
name = "rustsync-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
rustsync-core = { path = "../rustsync-core" }
clap = { version = "4", features = ["derive"] }
rustsync-protocol = { version = "0.1.0", path = "../rustsync-protocol" }
rustsync-client = { version = "0.1.0", path = "../rustsync-client" }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
url = "2"

[dev-dependencies]
hex = "0.4.3"
sha2 = "0.11"
tempfile = "3"
